logging:
  file:
    name: app.log
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: 8080
spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:test_db
    platform: org.hibernate.dialect.PostgreSQL95Dialect
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console.enabled: true
    show-sql: true